### PR TITLE
use SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE to retry when SQLITE_OPEN_READWRITE fails on native platforms.

### PR DESCRIPTION
**Pull request by nbransby**

### CODE REVIEW

**Comment by qiaoyuang** [comment]
Hi, I have seen your commits. But, after your modification, if a user set `isReadOnly = true`, he will get a writable database on Android, and a read-only database on the native platform. If it has the big difference on different platforms, I don't think that is a good idea.

And, I don't understand if I set `isReadOnly = false`, why the code would try to open the database twice with the same flags(`sqliteCreateFlags`).

**Comment by nbransby** [comment]
Good points, what about now? Sorry I am doing all these edits in the GitHub web editor - you'll definitely want to squash when merging!

**Comment by qiaoyuang** [comment]
Yeah, It's OK. Let's run a round workflow.

**Comment by nbransby** [comment]
@qiaoyuang are you able to create a new release today? We need the fix asap, otherwise we'll try and publish one internally

**Comment by qiaoyuang** [comment]
Yes, I am planning to do this. Do you mind me updating the Kotlin version to 1.9.10 in this release version?

**Comment by nbransby** [comment]
Great, yes thats fine, we are already using 1.9.10

**Comment by qiaoyuang** [comment]
Hi, @nbransby. I submitted a PR for this new release. I commented out these code in NativeDatabase:

```
if ((sqliteFlags and SQLITE_OPEN_READWRITE > 0) && sqlite3_db_readonly(db, null) != 0) {
       sqlite3_close_v2(db)
       throw sqliteException("Could not open the database in read/write mode")
}
```

Because, I think we should return a read-only database object to users when OS ban the writing permission or the situation of full disk. So, we don't check whether the database is writable anymore. You can review my code in [there](https://github.com/ctripcorp/SQLlin/pull/52/commits/160903df92169e2c6727f810a5c12102389c8f95#diff-1385c50e4a06f1f0c13359b4ef9f0a217d12d12cb73842dbc13addee6bc28077). And, I also fix the format of code.

**Pull request merged**
